services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: mokart-app
    ports:
      - "8000:3000"
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: mokart-web
    ports:
      - "8080:3000"
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: mokart-api
    ports:
      - "8081:5000"
    volumes:
      - ./api:/app
    restart: unless-stopped
