services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: mokart-web
    ports:
      - "9980:3000"
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: mokart-api
    ports:
      - "9981:5000"
    volumes:
      - ./api:/app
    restart: unless-stopped
